### PR TITLE
Send mouse movements to html

### LINKED ISSUE #26: Not able to resize drag over viewport
This issue is to fix not being able to resize drag over the viewport/engine render. (mentioned here: https://github.com/exokitxr/studio/pull/24#issuecomment-500277097)

visual reference gif:
studioconsolecss3

### PR DESCRIPTION
**Pull request by chrisplatorres**
This PR fixes sending mouse movements only when orbit controls present.

Closes #26

### CODE REVIEW

**Comment by modulesio** [comment]
Do we actually want to do that though? If we send the events while dragging we will be both dragging exokit and highlighting the page at the same time...

**Comment by chrisplatorres** [comment]
The drag is only at the very top/edge of console, where text could not be highlighted.

**Comment by modulesio** [comment]
But this code applies to all drags, no? So doing an orbit will highlight things on the page depending on how we move around.

**Comment by chrisplatorres** [comment]
This code only applies when the target is the UI: https://github.com/exokitxr/studio/blob/8be765b5611e79ac98a7fdc0c1cbad97e5ba840b/index.html#L1219

**Comment by modulesio** [comment]
`ui` seems to only mean "not locked into XR mode" -- I might be mistaken but it seems this this dragging would still happen on orbiting.

**Comment by chrisplatorres** [comment]
note from discord:

> we shouldn't be sending extra HTML events while we do exokit operations
> I can totally see the HTML having more complex handlers later and then dragging exokit will lag things despite having nothing to do with the HTML

**Pull request merged**
